spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
          allowed-origins: "*"
          allowed-methods: "*"
          allowed-headers: "*"
          allow-credentials: true
      # Integration with eureka to automatically discover all the routes of the microservices
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
#  Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    
#  Server configuration
server:
  port: 8080
