spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Integration with eureka to automatically discover all the routes of the microservices
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
#  Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    
#  Server configuration
server:
  port: 8080
